before:
  hooks:
    - go mod download

builds:
  - id: google-cloud-proto-scrubber
    binary: google-cloud-proto-scrubber
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  github:
  prerelease: auto
